"use client";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";

type Store = { id:string; name:string; region:string; dealer:string; owner:string; level:string; products:string[]; visit:string; status:"正常"|"待跟进" };
type Visit = { id:string; storeId:string; storeName:string; date:string; result:string; note:string };
const seed:Store[]=[
  {id:"MD001",name:"东区防水建材门店001",region:"东区",dealer:"杭州新材贸易",owner:"王晨",level:"S",products:["A产品","B产品","E产品","I产品"],visit:"今天 09:42",status:"正常"},
  {id:"MD002",name:"南区防水建材门店002",region:"南区",dealer:"宁波甬城代理",owner:"李杰",level:"S",products:["B产品","C产品","E产品","I产品"],visit:"昨天 16:18",status:"待跟进"},
  {id:"MD003",name:"西区防水建材门店003",region:"西区",dealer:"嘉兴恒盛建材",owner:"赵一鸣",level:"A",products:["A产品","D产品","F产品"],visit:"8 月 16 日",status:"正常"},
  {id:"MD004",name:"北区防水建材门店004",region:"北区",dealer:"绍兴越达贸易",owner:"陈浩",level:"A",products:["C产品","G产品","J产品","K产品"],visit:"尚未拜访",status:"正常"},
];

export default function Home(){
  const [stores,setStores]=useState(seed),[activeId,setActiveId]=useState("MD001"),[nav,setNav]=useState("门店档案"),[query,setQuery]=useState(""),[editing,setEditing]=useState<Store|null>(null),[notice,setNotice]=useState(""),[visits,setVisits]=useState<Visit[]>([]);
  useEffect(()=>{const v=localStorage.getItem("landun-stores-v2");if(v)setStores(JSON.parse(v));const h=localStorage.getItem("landun-visits");if(h)setVisits(JSON.parse(h));},[]);
  useEffect(()=>{localStorage.setItem("landun-stores-v2",JSON.stringify(stores));},[stores]);useEffect(()=>{localStorage.setItem("landun-visits",JSON.stringify(visits));},[visits]);
  const filtered=useMemo(()=>stores.filter(s=>`${s.id}${s.name}${s.region}${s.dealer}${s.products.join("")}`.toLowerCase().includes(query.toLowerCase())),[stores,query]);
  const active=stores.find(s=>s.id===activeId)||filtered[0]||stores[0];
  const recommendations=useMemo(()=>stores.map(s=>{let score=0,reasons:string[]=[];if(s.status==="待跟进"){score+=45;reasons.push("待跟进");}if(s.visit.includes("尚未")){score+=35;reasons.push("从未拜访");}else if(s.visit.includes("昨天")){score+=24;reasons.push("昨日拜访");}else if(s.visit.includes("8 月")){score+=18;reasons.push("超过 3 天");}if(s.products.length<=2){score+=15;reasons.push("产品偏少");}if(s.level==="S"){score+=5;reasons.push("重点门店");}return{store:s,score,reasons:reasons.slice(0,2)};}).sort((a,b)=>b.score-a.score),[stores]);
  const toast=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(""),2600)};
  function importFile(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=x=>{try{const wb=XLSX.read(x.target?.result,{type:"array"}),sheet=wb.SheetNames.includes("出货明细")?"出货明细":wb.SheetNames[0],rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[sheet],{defval:""}),map=new Map<string,Store>();rows.forEach(row=>{const id=String(row["门店编号"]||row["门店名称"]||"");const s=map.get(id)||{id,name:String(row["门店名称"]||"未命名门店"),region:String(row["区域"]||"待补充"),dealer:String(row["代理商"]||"未关联代理商"),owner:String(row["业务员"]||"待补充"),level:String(row["门店等级"]||"-"),products:[],visit:"尚未拜访",status:"正常"};const p=String(row["产品名称"]||row["产品代码"]||"");if(p&&!s.products.includes(p))s.products.push(p);map.set(id,s)});const next=[...map.values()];if(!next.length)throw 0;setStores(next);setActiveId(next[0].id);setNav("门店档案");toast(`已导入 ${next.length} 家门店`)}catch{toast("导入失败，请确认含有“出货明细”页")}};r.readAsArrayBuffer(f);e.target.value=""}
  function recordVisit(s:Store){const result=prompt("本次拜访结果","已完成拜访");if(result===null)return;const note=prompt("备注（可选）","")||"",date="今天 "+new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});setVisits(v=>[{id:String(Date.now()),storeId:s.id,storeName:s.name,date,result,note},...v]);setStores(v=>v.map(x=>x.id===s.id?{...x,visit:date,status:result.includes("待")||result.includes("报价")?"待跟进":"正常"}:x));toast("拜访记录已保存")}
  function save(){if(!editing)return;setStores(v=>v.map(s=>s.id===editing.id?editing:s));setEditing(null);toast("门店资料已保存")}
  return <main className="shell"><aside className="side"><div className="logo"><b>澜</b><div><strong>澜盾防水</strong><small>经销商工作台</small></div></div><label className="side-label">工作台</label>{["总览","门店档案","订单导入","拜访记录"].map(n=><button className={`nav ${nav===n?"on":""}`} key={n} onClick={()=>setNav(n)}><i>{n==="总览"?"⌂":n==="门店档案"?"▦":n==="订单导入"?"↥":"✓"}</i>{n}</button>)}<div className="side-foot">● 数据已同步<div className="person"><b>林</b><span>林晓峰<br/><small>销售主管</small></span></div></div></aside><section className="main"><header className="header"><div><small>2026 年 8 月 19 日 · 星期三</small><h1>{nav}</h1></div><div className="actions"><button className="outline" onClick={()=>document.getElementById("upload")?.click()}>↥ 导入出货表</button><input id="upload" hidden type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/><button className="solid" onClick={()=>{const s={id:`NEW${stores.length+1}`,name:"新建门店",region:"待补充",dealer:"待关联代理商",owner:"待填写",level:"A",products:[],visit:"尚未拜访",status:"待跟进" as const};setStores([s,...stores]);setActiveId(s.id);setEditing(s)}}>＋ 新建门店</button></div></header>{nav==="拜访记录"?<VisitPanel data={recommendations} visits={visits} onVisit={recordVisit}/>:nav==="订单导入"?<div className="empty-page"><div>↥</div><h2>订单导入</h2><p>上传代理商出货表，系统会自动按“门店名称”归类产品。</p><label className="solid">选择出货表<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/></label></div>:<StorePanel stores={stores} filtered={filtered} active={active} activeId={activeId} setActiveId={setActiveId} query={query} setQuery={setQuery} setEditing={setEditing} setStores={setStores} onVisit={recordVisit}/>}</section>{editing&&<div className="backdrop" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-title"><div><small>编辑门店档案</small><h2>{editing.name}</h2></div><button onClick={()=>setEditing(null)}>×</button></div><label>门店名称<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><div className="form-grid"><label>编号<input value={editing.id} onChange={e=>setEditing({...editing,id:e.target.value})}/></label><label>区域<input value={editing.region} onChange={e=>setEditing({...editing,region:e.target.value})}/></label><label>代理商<input value={editing.dealer} onChange={e=>setEditing({...editing,dealer:e.target.value})}/></label><label>负责人<input value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}/></label></div><label>在售产品（逗号分隔）<textarea value={editing.products.join("，")} onChange={e=>setEditing({...editing,products:e.target.value.split(/[，,]/).map(x=>x.trim()).filter(Boolean)})}/></label><div className="modal-actions"><button onClick={()=>setEditing(null)}>取消</button><button className="solid" onClick={save}>保存修改</button></div></div></div>}{notice&&<div className="notice">✓　{notice}</div>}</main>
}

function StorePanel({stores,filtered,active,activeId,setActiveId,query,setQuery,setEditing,setStores,onVisit}:{stores:Store[];filtered:Store[];active:Store;activeId:string;setActiveId:(x:string)=>void;query:string;setQuery:(x:string)=>void;setEditing:(x:Store)=>void;setStores:React.Dispatch<React.SetStateAction<Store[]>>;onVisit:(s:Store)=>void}){return <div className="page"><div className="summary"><div><small>门店总数</small><strong>{stores.length}</strong><span>家门店档案</span></div><div><small>已记录产品</small><strong>{new Set(stores.flatMap(s=>s.products)).size}</strong><span>个不同产品</span></div><div><small>待跟进</small><strong className="orange">{stores.filter(s=>s.status==="待跟进").length}</strong><span>家需要回访</span></div><div><small>本月导入</small><strong>2,468</strong><span>条出货明细</span></div></div><div className="workspace"><div className="list-panel"><div className="panel-head"><div><h2>门店货品台账</h2><p>每家门店卖什么，一眼看清</p></div><span className="hint">导入清单可随时更新</span></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索门店、编号、代理商或产品"/></div><div className="count">全部门店 <b>{filtered.length}</b></div>{filtered.map(s=><button className={`store ${activeId===s.id?"selected":""}`} key={s.id} onClick={()=>setActiveId(s.id)}><span className="store-icon">{s.name[0]}</span><span className="store-name"><b>{s.name}</b><small>{s.id} · {s.region}</small></span><span className="tags">{s.products.slice(0,3).map(p=><em key={p}>{p}</em>)}<small>{s.products.length} 个产品</small></span><span className={`state ${s.status===`正常`?`good`:`wait`}`}>{s.status}</span><i>›</i></button>)}</div><div className="detail"><div className="detail-head"><div><small>门店档案 · {active.id}</small><h2>{active.name}</h2><p>{active.region}　/　{active.dealer}</p></div><button className="edit" onClick={()=>setEditing({...active})}>编辑资料　✎</button></div><div className="owner"><b>{active.owner[0]}</b><span>负责人<br/><strong>{active.owner}</strong></span><span className="last">最近拜访<br/><strong>{active.visit}</strong></span></div><div className="products-title"><h3>已铺产品 <b>{active.products.length}</b></h3><button onClick={()=>{const p=prompt("新增产品名称");if(p)setStores(v=>v.map(s=>s.id===active.id?{...s,products:[...s.products,p]}:s))}}>＋ 添加产品</button></div><div className="products">{active.products.map((p,i)=><div className="product" key={p}><b className={`picon p${i%5}`}>{p[0]}</b><span><strong>{p}</strong><small>来自出货明细 · 已记录</small></span><button onClick={()=>setStores(v=>v.map(s=>s.id===active.id?{...s,products:s.products.filter(x=>x!==p)}:s))}>×</button></div>)}</div><div className="detail-foot"><span>门店等级 <b>{active.level}</b></span><button className="visit-btn" onClick={()=>onVisit(active)}>✓ 记录本次拜访</button></div></div></div></div>}

function VisitPanel({data,visits,onVisit}:{data:{store:Store;score:number;reasons:string[]}[];visits:Visit[];onVisit:(s:Store)=>void}){return <div className="page visit-page"><div className="visit-hero"><div><small>今日工作建议</small><h2>今日推荐拜访</h2><p>优先处理待跟进、从未拜访和产品覆盖偏少的门店。</p></div><strong>{Math.min(3,data.length)}<small> 家建议</small></strong></div><div className="visit-grid"><div><div className="section-title"><h3>推荐顺序</h3><span>综合评分</span></div>{data.slice(0,6).map((x,i)=><div className="recommend" key={x.store.id}><b className="rank">{String(i+1).padStart(2,"0")}</b><div><strong>{x.store.name}</strong><small>{x.store.id} · {x.store.region} · {x.store.dealer}</small><div>{x.reasons.map(r=><em key={r}>{r}</em>)}</div></div><b className="score">{x.score}<small>优先分</small></b><button className="small-btn" onClick={()=>onVisit(x.store)}>记录拜访</button></div>)}</div><div className="history"><div className="section-title"><h3>最近拜访记录</h3><span>{visits.length} 条</span></div>{visits.slice(0,7).map(v=><div className="history-row" key={v.id}><b>✓</b><span><strong>{v.storeName}</strong><small>{v.date} · {v.result}</small></span></div>)}{!visits.length&&<p className="no-history">完成一次拜访后，记录会显示在这里。</p>}</div></div></div>}
